minimum_pre_commit_version: 3.2.0 # necessitated by Lucas-C's hooks
default_install_hook_types: [pre-commit, pre-push]
exclude: |
  (?x)^(
      alpaka/.*|
      thirdParty/.*
  )$
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: no-commit-to-branch
        args: [-b, dev]
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: mixed-line-ending
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-tabs
      - id: remove-tabs
      - id: forbid-crlf
      - id: remove-crlf
  - repo: https://github.com/brutus/enforce-ascii
    rev: v0.2.1
    hooks:
      - id: enforce-ascii
        types_or: [file]
        exclude_types: [rst, tex, tsv, jupyter, markdown]
        exclude: .zenodo.json
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/google/yamlfmt
    rev: v0.13.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
