name: Continuous Integration
on: [push, pull_request]
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.18.2
        with:
          exclude: "./thirdParty ./alpaka"
          clangFormatVersion: 18
